// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx-M5xkIbmjesp-0ns-bOkd4Ga7uAXv0c',
    appId: '1:1081318479617:web:8da2d32f30c5e45d4eed00',
    messagingSenderId: '1081318479617',
    projectId: 'solar-power-91ffa',
    authDomain: 'solar-power-91ffa.firebaseapp.com',
    storageBucket: 'solar-power-91ffa.appspot.com',
    measurementId: 'G-T3RV8NY702',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHc0E6My06eyocJeHgELWNbwf8E9YhRs0',
    appId: '1:1081318479617:android:3e8e04d0fc32cbac4eed00',
    messagingSenderId: '1081318479617',
    projectId: 'solar-power-91ffa',
    storageBucket: 'solar-power-91ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dEL1lkeAr0POUDnwkt_9BfbWvr3JQqA',
    appId: '1:1081318479617:ios:b63bbbce59582b4a4eed00',
    messagingSenderId: '1081318479617',
    projectId: 'solar-power-91ffa',
    storageBucket: 'solar-power-91ffa.appspot.com',
    iosBundleId: 'com.example.projectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7dEL1lkeAr0POUDnwkt_9BfbWvr3JQqA',
    appId: '1:1081318479617:ios:73d63e798771535b4eed00',
    messagingSenderId: '1081318479617',
    projectId: 'solar-power-91ffa',
    storageBucket: 'solar-power-91ffa.appspot.com',
    iosBundleId: 'com.example.projectTest.RunnerTests',
  );
}
