// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwp9KjCN4cSqspF9HDs9UjnEt5uBRo_Ug',
    appId: '1:473883112738:web:62a69594d57ca334e6e17b',
    messagingSenderId: '473883112738',
    projectId: 'grad-projectt',
    authDomain: 'grad-projectt.firebaseapp.com',
    storageBucket: 'grad-projectt.appspot.com',
    measurementId: 'G-8DZSJW6QVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxk3igXt4CGX97UzgOxqz73co-2xmc__M',
    appId: '1:473883112738:android:5e74a235febec5a2e6e17b',
    messagingSenderId: '473883112738',
    projectId: 'grad-projectt',
    storageBucket: 'grad-projectt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEDP29z8Xb26ppmiI7cKqwJAXrHnHPab4',
    appId: '1:473883112738:ios:f2f11ec74a0a5a71e6e17b',
    messagingSenderId: '473883112738',
    projectId: 'grad-projectt',
    storageBucket: 'grad-projectt.appspot.com',
    iosBundleId: 'com.example.projectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEDP29z8Xb26ppmiI7cKqwJAXrHnHPab4',
    appId: '1:473883112738:ios:2522f7ca08f1f33de6e17b',
    messagingSenderId: '473883112738',
    projectId: 'grad-projectt',
    storageBucket: 'grad-projectt.appspot.com',
    iosBundleId: 'com.example.projectTest.RunnerTests',
  );
}
